### ISSUE TITLE
TreeView crashes

### ISSUE THREAD

**Issue by StepanHokobyan** [microsoft/Xaml-Controls-Gallery#617]
Hell I'm trying to use TreeView control but it crashes with this error

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key TabViewButtonBackground [Line: 28 Position: 10]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at XamlTestingApp.MainPage.InitializeComponent()
   at XamlTes

To get this error just use TreeView in UWP application and it will crash the app.
Hope you will fix it)))

**Comment by chingucoding** [comment]
I think this issue is better suited for the [WinUI repository](https://github.com/microsoft/microsoft-ui-xaml) as this seems related to WinUI and not specifically the XAML Controls Gallery.

Does this issue occur in a WinUI 2/UWP app or a WinUI 3 app? If it's a WinUI 3 app, it might be [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/2957). If you are using WinUI 2, can you try upgrading WinUI 2 or try using a prerelease if you are using a release build? I think this happened with WinUI 2.4 and was fixed after that, but not entirely sure.
